package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"strconv"

	"github.com/MinhDuy27/Ecommerce-App/domain"
	"github.com/MinhDuy27/Ecommerce-App/graph/model"
	"github.com/MinhDuy27/Ecommerce-App/internal/dto"
)

// SignUp is the resolver for the SignUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input *model.NewUser) (*model.Message, error) {
	logindto := dto.Logindto{
		Email:    input.Email,
		Password: input.Password,
	}
	SignUpdto := dto.SignUpdto{
		Logindto: logindto,
		Phone:    input.Phone,
	}
	value, err := r.Usv.SignUp(SignUpdto)
	if err != nil {
		return nil, err
	}
	message := model.Message{
		Message: value,
	}
	return &message, nil
}

// UpDate is the resolver for the UpDate field.
func (r *mutationResolver) UpDate(ctx context.Context, input *model.UpdateUser) (*model.Message, error) {
	User := domain.User{
		FirstName: func() string {
			if input.FirstName != nil {
				return *input.FirstName
			}
			return ""
		}(),
		LastName: func() string {
			if input.LastName != nil {
				return *input.LastName
			}
			return ""
		}(),
		Phone: func() string {
			if input.Phone != nil {
				return *input.Phone
			}
			return ""
		}(),
	}
	id := input.ID
	uint_id, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}
	_, error := r.Usv.Repo.FindUserById(uint(uint_id))
	if error != nil {
		return &model.Message{}, error
	}
	_, error = r.Usv.Repo.UpdateUser(uint(uint_id), User)
	if error != nil {
		return &model.Message{}, error
	}
	message := model.Message{
		Message: "update success",
	}
	return &message, nil
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	uint_id, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}
	value, err := r.Usv.GetProfilesByID(uint(uint_id))
	if err != nil {
		return nil, err
	}
	user := model.User{
		Email:     value.Email,
		FirstName: value.FirstName,
		LastName:  value.LastName,
		Phone:     value.Phone,
	}
	return &user, nil
}

// Login is the resolver for the Login field.
func (r *queryResolver) Login(ctx context.Context, input *model.Login) (*model.Message, error) {
	logindto := dto.Logindto{
		Email:    input.Email,
		Password: input.Password,
	}
	message, err := r.Usv.Login(logindto)
	if err != nil {
		return nil, err
	}
	Message := model.Message{
		Message: message,
	}
	return &Message, nil
}

// GetVerificationCode is the resolver for the GetVerificationCode field.
func (r *queryResolver) GetVerificationCode(ctx context.Context, id string) (*model.Message, error) {
	uint_id, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}
	user, error := r.Usv.GetProfilesByID(uint(uint_id))
	if error != nil {
		return nil, error
	}
	code, error := r.Usv.GetVerificationCode(user)
	if error != nil {
		return nil, error
	}
	string_Val := strconv.FormatUint(uint64(code), 10)
	message := model.Message{
		Message: string_Val,
	}
	return &message, nil
}

// Verification is the resolver for the Verification field.
func (r *queryResolver) Verification(ctx context.Context, input *model.Verify) (*model.Message, error) {
	uint_id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	_, err = r.Usv.GetProfilesByID(uint(uint_id))
	if err != nil {
		return nil, err
	}
	uint_code, err := strconv.ParseUint(input.Code, 10, 64)
	if err != nil {
		return nil, err
	}
	err = r.Usv.VerifyCode(uint(uint_id), uint(uint_code))
	if err != nil {
		return nil, err
	}
	message := model.Message{
		Message: "verification success",
	}
	return &message, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
