// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type Message struct {
	Message string `json:"Message"`
}

type Mutation struct {
}

type NewUser struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
	Phone    string `json:"Phone"`
}

type Query struct {
}

type UpdateUser struct {
	ID        string  `json:"id"`
	FirstName *string `json:"FirstName,omitempty"`
	LastName  *string `json:"LastName,omitempty"`
	Phone     *string `json:"Phone,omitempty"`
}

type User struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Phone     string `json:"Phone"`
	Email     string `json:"Email"`
}

type Verify struct {
	ID   string `json:"id"`
	Code string `json:"Code"`
}
