// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	CartID string    `json:"CartID"`
	Item   []*string `json:"Item"`
}

type Login struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type MalCart struct {
	UserID string  `json:"UserID"`
	CartID *string `json:"CartID,omitempty"`
}

type MalProcutInCart struct {
	UserID    string `json:"UserID"`
	CartID    string `json:"CartId"`
	ProductID string `json:"ProductID"`
	Quantity  int    `json:"Quantity"`
}

type Message struct {
	Message string `json:"Message"`
}

type Mutation struct {
}

type NewProduct struct {
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	Price       float64 `json:"Price"`
	Quantity    int     `json:"Quantity"`
	ImageURL    string  `json:"ImageURL"`
}

type NewUser struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
	Phone    string `json:"Phone"`
}

type Product struct {
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	Price       float64 `json:"Price"`
	Quantity    int     `json:"Quantity"`
	ImageURL    string  `json:"Image_url"`
}

type Query struct {
}

type Transaction struct {
	UserID       int      `json:"UserID"`
	Amount       int      `json:"Amount"`
	TotalPrice   float64  `json:"TotalPrice"`
	Discount     float64  `json:"Discount"`
	ShippingCost float64  `json:"ShippingCost"`
	TotalCost    float64  `json:"TotalCost"`
	Items        []string `json:"Items"`
}

type UpdateProduct struct {
	Name        *string  `json:"Name,omitempty"`
	Description *string  `json:"Description,omitempty"`
	Price       *float64 `json:"Price,omitempty"`
	Quantity    *int     `json:"Quantity,omitempty"`
	ImageURL    *string  `json:"ImageURL,omitempty"`
}

type UpdateUser struct {
	FirstName *string `json:"FirstName,omitempty"`
	LastName  *string `json:"LastName,omitempty"`
	Phone     *string `json:"Phone,omitempty"`
}

type User struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Phone     string `json:"Phone"`
	Email     string `json:"Email"`
}

type Verify struct {
	ID   string `json:"id"`
	Code string `json:"Code"`
}
