// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type Message struct {
	Message string `json:"Message"`
}

type Mutation struct {
}

type NewProduct struct {
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	Price       float64 `json:"Price"`
	Quantity    int     `json:"Quantity"`
	ImageURL    string  `json:"ImageURL"`
}

type NewUser struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
	Phone    string `json:"Phone"`
}

type Product struct {
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	Price       float64 `json:"Price"`
	Quantity    int     `json:"Quantity"`
	ImageURL    string  `json:"Image_url"`
}

type Query struct {
}

type UpdateProduct struct {
	Name        *string  `json:"Name,omitempty"`
	Description *string  `json:"Description,omitempty"`
	Price       *float64 `json:"Price,omitempty"`
	Quantity    *int     `json:"Quantity,omitempty"`
	ImageURL    *string  `json:"ImageURL,omitempty"`
}

type UpdateUser struct {
	ID        string  `json:"id"`
	FirstName *string `json:"FirstName,omitempty"`
	LastName  *string `json:"LastName,omitempty"`
	Phone     *string `json:"Phone,omitempty"`
}

type User struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Phone     string `json:"Phone"`
	Email     string `json:"Email"`
}

type Verify struct {
	ID   string `json:"id"`
	Code string `json:"Code"`
}
