// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	Message string `json:"Message"`
}

type Mutation struct {
}

type NewUser struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type Query struct {
}

type User struct {
	FirstName *string `json:"FirstName,omitempty"`
	Lastname  *string `json:"Lastname,omitempty"`
	Phone     *string `json:"Phone,omitempty"`
	Email     string  `json:"Email"`
}
